GET http://localhost:3001/api/persons/

###

DELETE http://localhost:3001/api/persons/60018f529825989e9e45a771

###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Thomas Müller",
    "number": "643-11336-12"
}

###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "number": "643-11336-12"
}

###
POST http://localhost:3001/sd/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Thomas Müller",
    "number": "643-11336-12"
}