GET http://localhost:3001/api/persons/

###

GET http://localhost:3001/api/persons/6002c67de71d7c2ea8a0b21e

###

GET http://localhost:3001/api/persons/malid

###

GET http://localhost:3001/api/persons/6002c67de71d7c2ea8a0b21f

###

DELETE http://localhost:3001/api/persons/6002cfbb52df353bcec33bd7

###


DELETE http://localhost:3001/api/persons/600188422afc5197041b0fdr

###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Thomas Müller",
    "number": "643-11336-12"
}

###

PUT http://localhost:3001/api/persons/6002d09852df353bcec33bd8 HTTP/1.1
content-type: application/json

{
    "name": "Thomas Müller",
    "number": "666"
}

###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "number": "643-11336-12"
}

###
POST http://localhost:3001/sd/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Thomas Müller",
    "number": "643-11336-12"
}